### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by CosmicDigital** [capawesome-team/capacitor-mlkit#49]
### Plugin(s)

- [X] Barcode Scanning
- [ ] Translation

### Did you test the latest version?

- [X] I use the latest version

### Platform(s)

- [X] Android
- [ ] iOS
- [ ] Web

### Current behavior

const { barcodes } = await BarcodeScanner.scan({
      formats: [BarcodeFormat.QrCode],
      lensFacing: LensFacing.Front,
    });
    
    The lensFacing.Front is not being supported in Android, but this works on iOS.

### Expected behavior

The LensFacing.Front works in iOS

### Reproduction

https://github.com/capawesome-team/.capacitor-app

### Steps to reproduce

1. Install plugin on ionic
2. Run the app on iOS, will scan with front cam by default
3. Run the app on Android, will not run with front cam

### Capacitor doctor

Latest Dependencies:

  @capacitor/cli: 5.0.5
  @capacitor/core: 5.0.5
  @capacitor/android: 5.0.5
  @capacitor/ios: 5.0.5

Installed Dependencies:

  @capacitor/cli: 5.0.4
  @capacitor/core: 5.0.4
  @capacitor/android: 5.0.4
  @capacitor/ios: 5.0.4

[success] iOS looking great! 👌
[error] Missing <manifest package=""> attribute in app/src/main

### Before submitting

- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment]
What exactly is your issue? Is the front camera not working on Android or is it just not the default direction? Please update your problem with more information.

**Comment by CosmicDigital** [comment]
Thank you @robingenz  for the reply

even though I have set lensFacing: LensFacing.Front

the back camera always opens

**Comment by robingenz** [comment]
The „scan(…)“ method currently officially only supports „formats“ as option and not „lensFacing“, see https://github.com/capawesome-team/capacitor-mlkit/tree/main/packages/barcode-scanning#scanoptions.
This is because it is not possible on Android with the SDK used. You should use the „startScan(…)“ method if you want to use the front camera.
We will also remove the undocumented iOS code.
For this reason I am closing this issue.
